### ISSUE TITLE
刷写后，无法实现配网

### ISSUE THREAD

**Issue by lingboly** [IoTDevice/phicomm_dc1#1]
正常刷写，中间没有问题
按照手机app（尝试了MIUI12 和IOS13.3）， 选择SmartConfig配网，找不到任何设备
硬件： DC1， 16M 闪存版本

**Comment by IoTServ** [comment]
手机有没有换个WiFi试试呢，可以试试加QQ群：251227638 
<img width="338" alt="QQ20201130-170208@2x" src="https://user-images.githubusercontent.com/20452619/100589396-03313200-332e-11eb-8fb0-09a63781366a.png">
发一下图片看下

**Comment by IoTServ** [comment]
加群验证：云易连
